version: '3.5'

services:

  apptest:
    container_name: apptest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '9999:9999'
